export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL'
